<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;


class Admin extends Model
{
    use HasFactory;
    protected $table = 'admin';
    protected $primaryKey = 'adminID';
    protected $fillable = ['adminName', 'adminUsername', 'adminEmail', 'adminPassword','adminPhone','adminStatus'];
    public $incrementing = false;

    public function save(array $options = [])
    {
        if (!$this->adminID)
            $this->adminID = Str::uuid()->toString();

        return parent::save($options); // TODO: Change the autogenerated stub
    }


}
