<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CustomerResponse extends Model
{
    use HasFactory;
    protected $table = 'customer_response';
    protected $primaryKey = 'customerResponseID';
    protected $fillable = ['invitationID','customerResponseEmail','customerResponseName', 'customerResponseDOB', 'customerResponseGender','customerResponseRegistrationToken' ,'customerResponseFav','customerResponseStatus'];
    public $incrementing = false;


    public function save(array $options = [])
    {
        if (!$this->customerResponseID)
            $this->customerResponseID = Str::uuid()->toString();

        return parent::save($options); // TODO: Change the autogenerated stub
    }


}
