<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;


class Invitation extends Model
{
    use HasFactory;
    protected $table = 'invitation';
    protected $primaryKey = 'invitationID';
    protected $fillable = ['adminID','email', 'invitationStatus'];
    public $incrementing = false;

    public function generateToken() {
        $this->link_token = $this->generateRandomString(25);
    }
    public function save(array $options = [])
    {
        if (!$this->invitationID)
            $this->invitationID = Str::uuid()->toString();

        return parent::save($options); // TODO: Change the autogenerated stub
    }

    private function generateRandomString($length = 10) {
        $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $charactersLength = strlen($characters);
        while(true){
            $randomString = '';
            for ($i = 0; $i < $length; $i++) {
                $randomString .= $characters[rand(0, $charactersLength - 1)];
            }
            $inv = Invitation::where('link_token', $randomString)->first();
            if(!$inv)break;
        }
        return $randomString;
    }



}
